server:
  port: 8080

spring:
  application:
    name: triage-api-dev
  
  datasource:
    url: jdbc:sqlserver://172.28.130.166:1433;databaseName=Triage;encrypt=false;trustServerCertificate=true
    username: ${DB_USERNAME:siphdbrw}
    password: ${DB_PASSWORD:S1ph2019}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

logging:
  level:
    com.triage: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
