server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: triage-api-prod
  
  datasource:
    url: ${DATABASE_URL:jdbc:sqlserver://172.28.130.166:1433;databaseName=Triage;encrypt=false;trustServerCertificate=true}
    username: ${DB_USERNAME:siphdbrw}
    password: ${DB_PASSWORD:S1ph2019}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false

logging:
  level:
    com.triage: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  file:
    name: logs/triage-api.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
